HeavyRPG = HeavyRPG or {}
local HRP = HeavyRPG

HRP.AuthCodes = {
    OK = "OK",
    INVALID_PAYLOAD = "INVALID_PAYLOAD",
    RATE_LIMIT = "RATE_LIMIT",
    VALIDATION_FAILED = "VALIDATION_FAILED",
    ACCOUNT_EXISTS = "ACCOUNT_EXISTS",
    SERIAL_LIMIT = "SERIAL_LIMIT",
    ACCOUNT_NOT_FOUND = "ACCOUNT_NOT_FOUND",
    PASSWORD_INVALID = "PASSWORD_INVALID",
    ACCOUNT_LOCKED = "ACCOUNT_LOCKED",
    ACCOUNT_BANNED = "ACCOUNT_BANNED",
    ALREADY_LOGGED_IN = "ALREADY_LOGGED_IN",
    SESSION_INVALID = "SESSION_INVALID",
    SERVER_ERROR = "SERVER_ERROR"
}
